### ISSUE TITLE
Misleading final instructions

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/week-1-day-5-discussion#4]
Students have been confused about the final instructions in this DQ: 
"For what reasons will the following method calls fail `:mongoose.tire_size = 5`, `mongoose.gears`, `Bicycle.bikes`, `Bicycle.style`? Restructure the class to fix the issues."

The call to Restructure the class to fix _all_ of these issues causes confusion for `Bicycle.style`. There is no logical way to restructure the class to allow `Bicycle.style` to work (Why would the blueprint for Bicycles have a style property?). Perhaps this was meant to be `Bicycle.styles` (plural)?

**Comment by maxwellbenton** [comment]
Hey @LaneMiller,

Good catch. Agreed, it would have to either be `mongoose.style` or `Bicycle.styles`. Considering the list is progressively more difficult, and this is the last one, I've switched it to `Bicycle.styles`.
